### PR TITLE
Rewrite comparator related logic. Introduce support to directory timestamps

### PR DESCRIPTION
**Pull request by NewEraCracker**
This commit adds the ability to show directory modification dates. Additionally introduces changes to comparator related logic and minor UI changes.

1. Ported the filemtime related code to directory object. PHP supports this well since version 5.2 (from my testing in Windows & Linux) and modern filesystems also update this timestamp when files are created, renamed or deleted on the respective directory level.

2. Rewrote all comparator related logic for a more sane approach to each problem the algorithm faces.

3. UI now only shows the arrow for the current selected sort by. User now clearly sees, with no room for 
doubts, which ordering is selected in the interface.

Feel free to comment on this changes and let me know if there are any improvements to be done.

### CODE REVIEW

**Comment by NewEraCracker** [comment]
I have added a commit that improves UI to word-wrap huge filenames without spaces in table elements. Additionally changed the colspan of the elements in the following way.

1. Master table
- Mobile view: Just one column. (previously was set to two)
- Standard view: Three or four columns depending on isDeleteAllowed setting (as previously).

2. Name field:
- Mobile view: Just one column for directories and files. (previously was set to two)
- Standard view: One column for files (as previously non-explicit), two columns for dirs (was previously three when timestamp wasn't shown, I then changed to two to allow timestamp space).

With regards to standard view, the reason for the changes are obvious. My previous 3 commits.

With regards to mobile view, it was a *de facto* one column from users point-of-view but for browsers point-of-view it was two columns and the column for name (that did not had specified span) was extended to fit in. The size label fluctuates in the bottom on that column.

Regards,
NewEraCracker

**Comment by marekrei** [comment]
Thanks!

**Comment by NewEraCracker** [comment]
Just one thing.

Some of your commits have been made with another email account in git config file. See here:
https://github.com/marekrei/encode-explorer/commits/master

I think it would be a good idea to add the new email address in your account panel, so those commits point back to your profile instead of not being assigned to any profile.

My two cents.

By the way, thanks for merging my commits. I did not do much extensive testing, and I'm running this on one of my development sites, so it was a good call to leave them off 6.4 version and include this in a future release instead.

Regards,
NewEraCracker

**Comment by marekrei** [comment]
Thanks, did that.

And thanks for contributing, you've done quite a bit of work. Sorry about some of the odd choices in my original code, it was written quite a few years ago :)

**Pull request merged**
